- set_fact:
    nginx_conf: /usr/local/etc/nginx
  when: ansible_distribution == 'FreeBSD'
- set_fact:
    nginx_conf: /etc/nginx
  when: ansible_distribution == 'Debian'

- name: install nginx (Debian)
  when: ansible_distribution == 'Debian'
  apt: pkg=nginx state=present force=yes
  notify: restart nginx
- name: install nginx (FreeBSD)
  when: ansible_distribution == 'FreeBSD'
  pkgng: name=nginx state=present
  notify: restart nginx
- name: enable nginx service
  when: ansible_distribution == 'FreeBSD'
  lineinfile: dest=/etc/rc.conf regexp=^nginx_enable= line=nginx_enable=YES
  notify: restart nginx
- name: install EPEL
  when: ansible_distribution == 'CentOS'
  yum: name=epel-release state=latest
- name: install nginx (CentOS)
  when: ansible_distribution == 'CentOS'
  yum: name=nginx state=latest
  notify: restart nginx

- name: Create www-data user
  user: >
    name=www-data
    createhome=no
    comment=www-data
    shell=/bin/false
    home={{ nginx_conf }}

- name: Create conf.d directory
  file: path={{ nginx_conf }}/conf.d state=directory
- name: Create sites-enabled directory
  file: path={{ nginx_conf }}/sites-enabled state=directory

- name: Create log directory
  file: path=/var/log/nginx state=directory

- name: Paste nginx config
  template: src=nginx.conf dest={{ nginx_conf }}/nginx.conf
  notify: reload nginx

- name: Remove default vhost
  file: path={{ nginx_conf }}/sites-enabled/default state=absent
  notify: reload nginx
