- name: http server
  hosts: all
  sudo: true
  roles:
  - { role: apache, tags: apache, when: ansible_hostname in groups.apache }
  - { role: nginx, tags: nginx, when: ansible_hostname in groups.nginx }
