- name: install mysql (Debian)
  when: ansible_distribution == 'Debian'
  apt: pkg={{ item }} state=present force=yes
  with_items:
  - mysql-common
  - mysql-server
  - mysql-client
  - libmysqlclient15-dev
  notify: restart mysql
